### ISSUE TITLE
parsing package.json modify the output folder

### ISSUE THREAD

**Issue by asturur** [jsdoc3/jsdoc#1477]
i have jsdoc 3.5.5 and i m running it like this

```
jsdoc --package lib/package.json lib/fabric.js README.md  -c jsdoc.json
```

this is my jsdoc.json

```json
{
  "templates": {
    "default": {
      "staticFiles": {
        "include": [
            "./jsdoc_template/include"
        ]
      }
    }
  },
  "opts": {
    "template": "./jsdoc_template/",
    "destination": "./docs/"
  }
}
```

What happens is that the files are outputted in:

```
docs/fabric/2.0.0-rc2/
```

that would be still ok if i could parse the output path and move them with  a script, but it looks like i not able to know where the files are generated.

Is possible to force output root as doc even with a package parsing?

**Comment by asturur** [comment]
i deleted those lines in publish.js

```
    // update outdir if necessary, then create outdir
    var packageInfo = ( find({kind: 'package'}) || [] ) [0];
    if (packageInfo && packageInfo.name) {
        outdir = path.join( outdir, packageInfo.name, (packageInfo.version || '') );
    }
```

is this the supported way to do so?

**Comment by Jaid** [comment]
I am currently struggling with the same problem. I want to tell JSDoc where my `package.json` is, so it dynamically includes module metadata in the generated HTMLs, but this also overwrites the destination path from `out/` to `out/PACKAGE/VERSION`, which is hard to process afterwards for certain build setups.

In my case: I use [Travis](https://travis-ci.org/Jaid/numbered-list) to generate the static documentation and upload it to [surge.sh](numbered-list.docs.j4id.com). The `index.html` must be in the Surge project root, so I  use `mv` to manually revert the destination path change.

.travis.yml
```yml
language: node_js
node_js:
  - '8'
cache: yarn
script: # && instead of YAML array, see: https://github.com/travis-ci/travis-ci/issues/1066
  - yarn jsdoc && mkdir -p surge-docs && mv out/*/*/** surge-docs
deploy:
  provider: surge
  project: ./surge-docs
  domain: numbered-list.docs.j4id.com
  skip_cleanup: true
```
